### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by scx**
Update to the latest version:
 - Provide `odfpy` `1.4.0`
 - Migrate to `Python3`

### CODE REVIEW

**Comment by scx** [comment]
bot, build org.gnome.OCRFeeder

**Comment by bochecha** [comment]
This seems like something way too big to carry downstream honestly.

Since this has been merged upstream, why not just wait for the next upstream release?

AFAIK the Flathub policy is to only package released software, not Git master.

**Comment by scx** [comment]
@bochecha 

> This seems like something way too big to carry downstream honestly.

This is why I waited until Joaquim Rocha takes care of it.
https://gitlab.gnome.org/GNOME/ocrfeeder/commit/8615aff3966dbfe24ed45eed6d34dc9b4e6b4e90

> Since this has been merged upstream, why not just wait for the next upstream release?

The last stable version was released in 2014, and it doesn't seem like the next one will appear anytime soon. And to be honest, **OCRFeeder** `0.8.1` is extremely buggy and unpolished (image preview doesn't match selection after unpapering page, scanning is mostly broken, spellchecker window doesn't work at all, program often uses a different engine than the one selected, etc.). This is mainly because the port from `PyGTK` (`Gtk+2`) to `PyGI` (`Gtk+3`) wasn't tested very well.

This is a very similar situation to e.g. **Aegisub**. The last version was released in 2014 and it is really buggy and outdated, so users often want to use more recent packages.

Anyway, just see what the manifest was before these updates:
https://github.com/flathub/org.gnome.OCRFeeder/blob/c94b23acaa0ea54f3b1f0c4cfb8f813a5c174acc/OCRFeeder.yaml#L9-L77

Over a dozen patches that have finally been merged upstream!
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/1

And it still was based on the git version from 2018!
https://github.com/flathub/org.gnome.OCRFeeder/blob/c94b23acaa0ea54f3b1f0c4cfb8f813a5c174acc/OCRFeeder.yaml#L6-L8
https://gitlab.gnome.org/GNOME/ocrfeeder/tree/51483c4b625c42b9bc04b2056b903a431b080935

Of course, we could use the stable version and apply only the most necessary patches, but it would be at least several dozen of them.

For example, the stable release still uses obsoleted `GNOME2` macros, as well as `GNOME Doc` instead of `Yelp`.
https://gitlab.gnome.org/GNOME/ocrfeeder/commit/cfc7bcf9a23c51d009717850df7049f3130ac951
https://gitlab.gnome.org/GNOME/ocrfeeder/commit/13c913a9d4818b484204d874e85fe0f1be6d3353

What's worse, the code has changed so much since 2014 that it is impossible to apply current patches without picking at least several patches from git master. And it would be insane to maintenance.

> AFAIK the Flathub policy is to only package released software, not Git master.

According to Flathub members, they "_bend this rule when it makes sense_".

There are plenty of reasons why we should use the `Python3` port.

First of all, **OCRFeeder** has been already ported to `Python3`, so new patches will require to use this port. And as you probably know, `Python2` has been already retired from maintenance.
https://pythonclock.org

In fact, Debian maintainers have already decided to switch to the `Python3` port. And it would be very shameful to have older packages than Debian. ;)
https://gitlab.gnome.org/GNOME/ocrfeeder/issues/10#note_609062
https://packages.debian.org/sid/ocrfeeder

Because of `Python2` is now outside of the **Freedesktop** runtime, we have to use the shared module.
https://github.com/flathub/shared-modules/blob/5a8d9cdb9be2881a64e6381c4f4bbfe2108ef0d0/python2.7/python-2.7.json
This means that we have to manually update the submodules, and it is not always possible, because we have to stick to the fixed version of others modules.
For example, `udev` was removed from the `shared-modules`, so we couldn't use it until upgrade the **GNOME** runtime to `3.34`.
https://github.com/flathub/shared-modules/commit/eb9db91c3fc5fd2e4ab4f0edbf9fcefa239c8ca2
However, it is not always possible.

For example, in November I've reported a bug in **Freedesktop** `19.08` (on which **GNOME** `3.34` is based).
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/921

It was "fixed" in early December, but in fact this bug still persisted until January 13.
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tags/freedesktop-sdk-19.08.6

Just for comparison:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/freedesktop-sdk-19.08.5/elements/components/pciutils.bst
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/freedesktop-sdk-19.08.6/elements/components/pciutils.bst#L23-38

Even if we could deal with `Python2` itself, there are a lot of problems with `Python2` modules. In fact, they require a lot of manual patching.

For example, for `python2-PyGObject` we should use `--no-use-pep517`... but only in the **GNOME** `3.34` runtime, because `pip2` in **GNOME** `3.32` doesn't support it:
```
no such option: --no-use-pep517
```
So we have no other choice than disable build isolation by the `--no-build-isolation` switch.
https://github.com/flathub/org.gnome.OCRFeeder/blob/0cd3944c38bcca5980727be683706ea96cd1e141/python2-PyGObject.yaml#L8-L11

And there is an another example:
https://github.com/flathub/org.gnome.OCRFeeder/blob/0cd3944c38bcca5980727be683706ea96cd1e141/python2-Pillow.yaml#L3-L13

All these things are not longer needed for `Python3` modules.

What is worse, more and more Python modules are dropping support for `Python2`. This has already happened for `Pillow`, where version `7.0.0` only supports `Python3`.
https://pypi.org/project/Pillow/7.0.0/#files
https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#python-2-7

So as you can see, the sooner we switch to `Python3`, the better.

**Comment by bochecha** [comment]
> So as you can see, the sooner we switch to Python3, the better.

As a professional Python dev for almost 10 years, I agree entirely with that sentiment in general.

[However](https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds):

> Flathub only hosts stable application releases, and not development snapshots.

You're building from Git master ([7f32b3be5733c321643ed11f301661504c34685d](https://gitlab.gnome.org/GNOME/ocrfeeder/commit/7f32b3be5733c321643ed11f301661504c34685d) as of writing this), and then adding **a lot** of patches on top.

That's very far from the Flathub policy.

Please ask upstream to make a new release, and build from that ASAP.

**Comment by scx** [comment]
@bochecha 

> [However](https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds):
> 
> > Flathub only hosts stable application releases, and not development snapshots.
> 
> You're building from Git master ([7f32b3be5733c321643ed11f301661504c34685d](https://gitlab.gnome.org/GNOME/ocrfeeder/commit/7f32b3be5733c321643ed11f301661504c34685d) as of writing this), and then adding **a lot** of patches on top.
> 
> That's very far from the Flathub policy.

Not really. Flathub members said that they "_bend this rule when it makes sense_".
https://archive.is/skQWo#selection-3723.3-3723.38

That is indeed the case.
https://github.com/flathub/org.flatpak.flat-manager-client/commit/cf9c0da213110c78b71fc9b2e00e3b998f809c1c

If you're specifically asking about migrating to Python 3, we've already had such a case.
https://github.com/flathub/org.sugarlabs.ReadETexts/commit/6ddae044fe351f1e379bbf7d3b2dab5f7c73f7a3

And here are more examples:
https://github.com/flathub/com.github.bcedu.valasimplehttpserver/blob/7ad9c90516b2831ab6549a3812f3eda18715f35a/com.github.bcedu.valasimplehttpserver.json#L24-L26
https://github.com/flathub/com.github.bcedu.vgrive/blob/287261c84b6b8a7e6cb6ec0d49e91e6db8f68cf8/com.github.bcedu.vgrive.json#L24-L26
https://github.com/flathub/com.github.birros.WebArchives/blob/deb03d15d3f647e396441086f2bdfdbaa969a6c0/com.github.birros.WebArchives.yml#L175-L177
https://github.com/flathub/com.github.calo001.fondo/blob/74f48d55657f11c90d4c98f42f2e8e491bfb8b24/com.github.calo001.fondo.json#L40-L42
https://github.com/flathub/com.github.JannikHv.Gydl/blob/7ff59619213c1c9ce59921bbea2ea762b8fa1dc6/com.github.JannikHv.Gydl.json#L61-L63
https://github.com/flathub/com.github.libresprite.LibreSprite/blob/34ca667179ce47826b4f4f4fafeb81d43573d942/com.github.libresprite.LibreSprite.yaml#L33-L35
https://github.com/flathub/com.github.ojubaorg.Othman/blob/fbcd6a6ee44290abc33c5b5fe520f91bb61ac3c3/com.github.ojubaorg.Othman.json#L55-L57
https://github.com/flathub/com.github.utsushi.Utsushi/blob/9397f6c682d095163137fa58a2cfbbf2c734906d/com.github.utsushi.Utsushi.json#L143-L145
https://github.com/flathub/com.jgraph.drawio.desktop/blob/ed0b6787ba53c514f4e792060b958ca438408a6d/com.jgraph.drawio.desktop.yaml#L52-L54
https://github.com/flathub/com.ozmartians.VidCutter/blob/64f1d16c6c8844a9c27b2321a5c8a07cee440568/com.ozmartians.VidCutter.json#L472-L475
https://github.com/flathub/de.create3000.titania/blob/2b78cf4c7bd7d438b8c01f805a1891237835cd93/de.create3000.titania.json#L424-L426
https://github.com/flathub/de.gunibert.Hackgregator/blob/0c9626433fe4415213979950b775c1978d4901c1/de.gunibert.Hackgregator.json#L58-L60
https://github.com/flathub/de.haeckerfelix.Fragments/blob/9a25d6f6a684cc8ad73cd8f5dd9b4d502ba84f92/de.haeckerfelix.Fragments.json#L62-L64
https://github.com/flathub/de.haeckerfelix.Remotely/blob/1c3860632add5ecff50668eefb1d606c81e5c4d2/de.haeckerfelix.Remotely.json#L43-L45
https://github.com/flathub/de.rwth_aachen.ient.RDPlot/blob/c6d2ff1cd9b693605d59254401c9316283a22789/de.rwth_aachen.ient.RDPlot.yaml#L152-L155
https://github.com/flathub/dk.tangramgames.mrrescue/blob/827c105bd8eabf481530c259bb3f3b3b879590b2/dk.tangramgames.mrrescue.json#L94-L96
https://github.com/flathub/fr.natron.Natron/blob/19a8ccf3d1d307eaac5c49239e33a509e5410c3b/fr.natron.Natron.json#L1125-L1127
https://github.com/flathub/id.sideka.App/blob/dfd7544f84e470858d3dac73687faf87c6058470/id.sideka.App.json#L71-L74
https://github.com/flathub/im.srain.Srain/blob/b157ac1e53198ed99164131432ff3d91f4621d0a/im.srain.Srain.yaml#L32-L35
https://github.com/flathub/io.github.mki1967.mki3dgame/blob/e3392d98fb5df6e80864d4315feb5588d293a229/io.github.mki1967.mki3dgame.json#L68-L71
https://github.com/flathub/io.github.trytonvanmeer.DungeonJournal/blob/6df4595db8ab00c09290f2e8b84e019b17002f2a/io.github.trytonvanmeer.DungeonJournal.json#L53-L55
https://github.com/flathub/io.gitlab.construo.construo/blob/7cc36b4a23afe0ff9e524a4f4bba5564cd7b0ebe/io.gitlab.construo.construo.json#L23-L25
https://github.com/flathub/io.gitlab.jstest_gtk.jstest_gtk/blob/82cc5b28a3324ddf186e994fc2a0b8e94b1d359f/io.gitlab.jstest_gtk.jstest_gtk.json#L32-L34
https://github.com/flathub/io.gitlab.sdl_jstest.sdl_jstest/blob/4604b065a1c2dd7649095ba539244d9a41c776bb/io.gitlab.sdl_jstest.sdl_jstest.json#L27-L29
https://github.com/flathub/io.gitlab.sdl_jstest.sdl2_jstest/blob/cf4d07cea6efb0e2e3954ed64b034dfc05d353a3/io.gitlab.sdl_jstest.sdl2_jstest.json#L26-L28
https://github.com/flathub/io.gitlab.windstille.Windstille-0_2/blob/596e14b38ca9b7fb3af5f135e45698777b308994/io.gitlab.windstille.Windstille-0_2.json#L40-L42
https://github.com/flathub/mx.pwmc.Svgvi/blob/404b13b7e6ac0ee02de101bbd3532c2aa84bbaf7/mx.pwmc.Svgvi.json#L103-L105
https://github.com/flathub/net.pcsx2.PCSX2/blob/ceeb246e2f736b4ba73d18186e04f9a70e644566/net.pcsx2.PCSX2.json#L157-L159
https://github.com/flathub/nl.g4d.Girens/blob/54fc3fabac36273e97628380495904d77a4e798c/nl.g4d.Girens.json#L298-L300
https://github.com/flathub/org.bitbucket.mystery_keeper.VapourSynthEditor/blob/4bc60ef524aef96cf17fc489fb7f6e45e9243e1a/org.bitbucket.mystery_keeper.VapourSynthEditor.yaml#L64-L66
https://github.com/flathub/org.clementine_player.Clementine/blob/23d65aaba7a667bede37c3d65a43aa29f3079b78/org.clementine_player.Clementine.yaml#L178-L180
https://github.com/flathub/org.DolphinEmu.dolphin-emu/blob/338f39ba8bfa809d230dee6f8b9c84a3b71b5f0d/org.DolphinEmu.dolphin-emu.json#L70-L72
https://github.com/flathub/org.flatpak.flat-manager-client/blob/cf9c0da213110c78b71fc9b2e00e3b998f809c1c/org.flatpak.flat-manager-client.json#L116-L118
https://github.com/flathub/org.flatpak.qtdemo/blob/16f08d9d2112f639cb94b814d46bc42735fc3951/org.flatpak.qtdemo.json#L22-L24
https://github.com/flathub/org.gnome.Builder/blob/818a423220a289d08597dbc54bde02b6001d8160/org.gnome.Builder.json#L596-L599
https://github.com/flathub/org.gnome.Shotwell/blob/203da55d4f506884150f4ff22a4b0e91e2ebec32/org.gnome.Shotwell.json#L158-L160
https://github.com/flathub/org.kde.gcompris/blob/881ba6ebb333285c5f0851f51307046bef1dbce1/org.kde.gcompris.json#L34-L36
https://github.com/flathub/org.laptop.TurtleArtActivity/blob/665cd5f73e59d966be73262ab5405a01f9b037ae/org.laptop.TurtleArtActivity.json#L106-L108
https://github.com/flathub/org.libretro.RetroArch/blob/7b14fd558b29e76d244f15406e9c6c7274587099/org.libretro.RetroArch.json#L73-L75
https://github.com/flathub/org.mobsya.ThymioSuite/blob/af5108286724e976d1cd885b30a47f1213b7439e/org.mobsya.ThymioSuite.json#L92-L94
https://github.com/flathub/org.olivevideoeditor.Olive/blob/aaa863e32e02b2546ca828de485190d4340c7c6f/org.olivevideoeditor.Olive.yaml#L81-L83
https://github.com/flathub/org.seul.pingus/blob/871b60d7a6cb27e5abb08d725b74a4f4cb59a81d/org.seul.pingus.json#L65-L67
https://github.com/flathub/org.sugarlabs.AbacusActivity/blob/7deb24adb98b2e303a6cdb0dd5a948fd0de07772/org.sugarlabs.AbacusActivity.json#L208-L210
https://github.com/flathub/org.sugarlabs.Maze/blob/22e214e651bc83953b04bcf45ae2bc1bf2333129/org.sugarlabs.Maze.json#L213-L215
https://github.com/flathub/org.sugarlabs.Measure/blob/c479ff064b194fa5fb6a0584f31ac91900a15ee6/org.sugarlabs.Measure.json#L266-L268
https://github.com/flathub/org.sugarlabs.ReadETexts/blob/6ddae044fe351f1e379bbf7d3b2dab5f7c73f7a3/org.sugarlabs.ReadETexts.json#L242-L244
https://github.com/flathub/org.sugarlabs.Sliderule/blob/cca24c96ffb6b26ca31201b0d6e1c106fcb6b8be/org.sugarlabs.Sliderule.json#L213-L215
https://github.com/flathub/org.sugarlabs.TurtlePondActivity/blob/d6a6c7685fdbf255031c3039658abc596966677d/org.sugarlabs.TurtlePondActivity.json#L213-L215
https://github.com/flathub/org.sugarlabs.Words/blob/050411dcf0e9b29f923cf4e0facce53cc5f45903/org.sugarlabs.Words.json#L245-L247
https://github.com/flathub/org.vranki.spectral/blob/9e63e33dbcb97c4c20b7632249a3789a544eb470/org.vranki.spectral.yaml#L22-L24
https://github.com/flathub/tv.kodi.Kodi/blob/db3ccb6d0d39c58579783962c2ad9ac25db3b163/tv.kodi.Kodi.yml#L123-L125

> Please ask upstream to make a new release, and build from that ASAP.

Of course, I can ask the project leader to produce a new release when he finally finds time to merge current Merge Requests.
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/3
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/4
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/5
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/6

However, I can't force him, nor any other developer, to start making releases. Both Red Hat and Debian maintainers have tried to, but have not been at all successful.

Please keep in mind that this package has been using the git version from the very beginning. It was accepted that way.
https://github.com/flathub/flathub/pull/825/files#diff-c569f64945f46445268082132b107401R6-R8

However, it should be noted that the git version mainly brings bug fixes and doesn't provide new functionality.

**Pull request merged**
