### PR TITLE
WIP: Update to Gnome 3.34

### PR DESCRIPTION
**Pull request by bochecha**
This updates to the 3.34 version of the GNOME runtime, adding missing dependencies and removing obsolete ones.

This also updates the bundled Python version to its latest release.

### CODE REVIEW

**Comment by bochecha** [comment]
Note that it doesn't build currently, because gnome-common has been removed from the 3.34 runtime.

Working on that…

**Comment by scx** [comment]
I'm working on updating the GNOME runtime. Please don't merge this PR. I will provide more details soon.

**Comment by bochecha** [comment]
@scx you're the one with merge power, not me. :stuck_out_tongue: 

I'll close this then, if you're already working on it.

When you update, do make sure you remove openjpeg and use the one from the runtime instead.

I'd appreciate if you pinged me as well at that point, as it would help me figure out what still needs to be done with regards to openjpeg. (I'm trying to either remove it from apps that use the GNOME runtime, or move all apps to the new shared-modules) :slightly_smiling_face:

**Comment by scx** [comment]
First of all, I want to improve the scanner support. That's why I've submitted a merge request for XSane.
https://github.com/flathub/flathub/pull/1111#issuecomment-520837857
Unfortunately, Flathub maintainers have been blocking it for no reason for several months.

Currently, I am working on scanner support for `Freedesktop` `19.08`, on which `GNOME` `3.34` is based.
There was a bug that I've reported a week ago with the proposed solution.
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/921
Now it is resolved (it was merged literally 3 hours ago!), but we still have to wait for the runtime image to be updated.

What's more, I want to add one additional dependency to OCRFeeder for deskewing scanned text documents. I also want to update the translations.
I estimate it will take several days. I will try to take your changes  into account. Thanks for your cooperation!

**Comment by scx** [comment]
Current status:
- [ ]  update components
  - [ ] update shared modules
    - [ ] update `python2`
  - [ ] update `enchant2`
  - [ ] update `ffmpeg`
  - [ ] update `GraphicsMagick`
  - [ ] update `ghostscript`
  - [ ] update `leptonica`
  - [ ] update `netpbm`
  - [ ] update `tesseract`
  - [ ] update `python2` modules
    - [ ] update `python2-Pillow`
    - [ ] update `python2-PyGObject`
    - [ ] update `python2-lxml`
    - [ ] update `pycairo`
    - [ ] update `reportlab`
  - [ ] update dictionaries
  - [ ] update fonts
  - [ ] fix `djvulibre`
  - [ ] fix `sane-backends`
  - [ ] remove `openjpeg`
- [ ] improve scanner support
- [ ] improve deskewing scanned text documents
- [ ] fix issue with spell checker
- [ ] update translations

**Comment by scx** [comment]
There were at least 3 bugs that prevent scanners to work. For now, I fixed one of them.

**Comment by scx** [comment]
@bochecha 
Finally finished.

Replaced by:
flathub/org.gnome.OCRFeeder#4
flathub/org.gnome.OCRFeeder#5
flathub/org.gnome.OCRFeeder#6
flathub/org.gnome.OCRFeeder#7

See also:
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/3
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/4
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/5
https://gitlab.gnome.org/GNOME/ocrfeeder/merge_requests/6

**Pull request closed without merging**
