### PR TITLE
Add backend for AirScan (eSCL) and WSD scanners

### PR DESCRIPTION
**Pull request by hadess**
Goes on top of https://github.com/flathub/org.gnome.OCRFeeder/pull/26 and https://github.com/flathub/org.gnome.OCRFeeder/pull/27

### CODE REVIEW

**Comment by hfiguiere** [comment]
do you need help merging this?

**Comment by hadess** [comment]
> do you need help merging this?

If it's directed at me, I definitely will, yes, as I don't have maintainer access to this repo.

I think that a review of the 2 other MRs would be a great first step, and would allow me to rebase this and make it more easily reviewable.

I don't have hardware to test this particular MR, but it copy/pastes the support from other scanner apps in Flathub that have the support.

Thanks!

**Comment by hadess** [comment]
This will need testing from someone with access to an AirScan scanner.

My next step will be to add support for Epson scanners (and I can test that).

**Comment by hfiguiere** [comment]
I don't have the hardware either.

I still have on my todo list to try to make a generic sane support for Flathub. But it's gonna take a bit to free up cycles to do so.

As for the Epson Scan drivers, It might be more complicated. They already hardcode the path in binary blobs like for the V600.

**Comment by hadess** [comment]
> I still have on my todo list to try to make a generic sane support for Flathub. But it's gonna take a bit to free up cycles to do so.

That was kind of the idea with this patchset. I took the most complete sane build out of all the apps in Flathub, and modified it until it had a single entry point that can be moved to `shared-modules`.

I'm unsure of how we could make this extensible so that the proprietary Epson driver could be used with any of the `sane` apps in Flathub, that's definitely something we'll want to figure out.

> As for the Epson Scan drivers, It might be more complicated. They already hardcode the path in binary blobs like for the V600.

Right, not going to be easy, but I've done my fair share of `LD_PRELOAD` hacks for Flathub, and there's always the possibility of using Ghidra and/or hand-patching binaries, we'll see.

> EpsonScan is there https://github.com/flathub/net.epson.epsonscan2/

Cool, I have a few things to scan urgently before I have time to investigate the above more.

**Comment by hfiguiere** [comment]
> > As for the Epson Scan drivers, It might be more complicated. They already hardcode the path in binary blobs like for the V600.
> 
> Right, not going to be easy, but I've done my fair share of `LD_PRELOAD` hacks for Flathub, and there's always the possibility of using Ghidra and/or hand-patching binaries, we'll see.

I patch the binary in two spot to replace `usr` with `app`. There is a python script for that.

> > EpsonScan is there https://github.com/flathub/net.epson.epsonscan2/
> 
> Cool, I have a few things to scan urgently before I have time to investigate the above more.

Let me know if it doesn't work for you. I only have one (USB) scanner to test it. (feel free to file issue or PR)

**Comment by hadess** [comment]
> I patch the binary in two spot to replace `usr` with `app`. There is a python script for that.

I saw that after making the comment, good job.

> Let me know if it doesn't work for you. I only have one (USB) scanner to test it. (feel free to file issue or PR)

I have a v600 as well, not sure my experience will differ too much from yours.

**Pull request merged**
